---
- name: Fill motd file with host data
  hosts: node1
  become: yes
  tasks:
    - name: Ensure motd.facts.j2 copied to managed host
      template:
        src: motd-facts.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
