---
- name: use apache_vhost role playbook
  hosts: node2
  become: yes

  pre_tasks:
    - debug:
        msg: 'Begining Webserver Configuration'

  roles:
    - apache_vhost

  post_tasks:
    - debug:
        msg: 'Webserver has been configured'
